name: "Neon Database Delete Branch"
author: "Neon Database"
description: "Deletes Neon Postgres branch with Id"
branding:
  icon: "box"
  color: "red"

inputs:
  project_id:
    required: true
    description: "The Neon project id"
  branch_id:
    description: "The Neon branch id"
    deprecationMessage: "The `branch_id` input is deprecated in favor of `branch`"
  api_key:
    description: "The Neon API key, read more at https://neon.tech/docs/manage/api-keys"
    required: true
  api_host:
    description: "The Neon API host"
    default: 'https://console.neon.tech/api/v2'
  branch:
    description: "The Neon branch name or id"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e  # v6.4.0
    - run: npm i -g --ignore-scripts neonctl@2.22.0
      shell: bash
    - name: Delete branch
      shell: bash
      env:
        NEON_API_KEY: ${{ inputs.api_key }}
        NEON_API_HOST: ${{ inputs.api_host }}
        INPUT_BRANCH: ${{ inputs.branch }}
        INPUT_BRANCH_ID: ${{ inputs.branch_id }}
        INPUT_PROJECT_ID: ${{ inputs.project_id }}
      run: |
        if [ -z "$INPUT_BRANCH" ]; then
          neonctl branches delete "$INPUT_BRANCH_ID" --project-id "$INPUT_PROJECT_ID"
        else
          neonctl branches delete "$INPUT_BRANCH" --project-id "$INPUT_PROJECT_ID"
        fi
